#!/bin/bash
if ! grep -q "^unixsocket /var/lib/redis/redis.sock" /etc/redis/redis.conf ; then
    sed -i -e 's/^\(#.\)\?port.*$/port 0/' /etc/redis/redis.conf
    sed -i -e 's/^\(#.\)\?unixsocket \/.*$/unixsocket \/var\/lib\/redis\/redis.sock/' /etc/redis/redis.conf
    sed -i -e 's/^\(#.\)\?unixsocketperm.*$/unixsocketperm 700/' /etc/redis/redis.conf
fi

greenbone-nvt-sync
greenbone-scapdata-sync
greenbone-certdata-sync

service openvas-manager stop
service openvas-scanner stop
service openvas-gsa stop

openvassd
openvasmd --migrate
openvasmd --progress --rebuild

killall --wait openvassd
sleep 5

service openvas-scanner start
service openvas-manager start
service openvas-gsa start

if ! openvasmd --get-users | grep -q ^admin$ ; then
    openvasmd --create-user=admin
fi
