#!/bin/bash
if ! grep -q "^unixsocket /var/lib/redis/redis.sock" /etc/redis/redis.conf ; then
    sed -i -e 's/^\(#.\)\?port.*$/port 0/' /etc/redis/redis.conf
    sed -i -e 's/^\(#.\)\?unixsocket \/.*$/unixsocket \/var\/lib\/redis\/redis.sock/' /etc/redis/redis.conf
    sed -i -e 's/^\(#.\)\?unixsocketperm.*$/unixsocketperm 700/' /etc/redis/redis.conf
fi

test -e /var/lib/openvas/CA/cacert.pem || openvas-mkcert -q
if (openssl verify -CAfile /var/lib/openvas/CA/cacert.pem \
    /var/lib/openvas/CA/servercert.pem |grep -q ^error); then
    openvas-mkcert -q -f
fi
greenbone-nvt-sync
greenbone-scapdata-sync
greenbone-certdata-sync
if ! test -e /var/lib/openvas/CA/clientcert.pem || \
    ! test -e /var/lib/openvas/private/CA/clientkey.pem; then
    openvas-mkcert-client -n -i
fi
if (openssl verify -CAfile /var/lib/openvas/CA/cacert.pem \
    /var/lib/openvas/CA/clientcert.pem |grep -q ^error); then
    openvas-mkcert-client -n -i
fi

service openvas-manager stop
service openvas-scanner stop
service openvas-gsa stop

openvassd
openvasmd --migrate
openvasmd --progress --rebuild

killall --wait openvassd
sleep 5

service openvas-scanner start
service openvas-manager start
service openvas-gsa start 

if ! openvasmd --get-users | grep -q ^admin$ ; then
    openvasmd --create-user=admin
fi
